React capstone project - Metrics webapp
DianaBeki/meal_point pull request #1
Opened 2023-08-26 10:17 UTC by DianaBeki

### I was able to do the following
Use React documentation.
Use React components.
Use React props.
Use React Router.
Connect React and Redux.
Handle events in a React app.
Write integration tests with a React testing library.
Use styles in a React app.
Use React life cycle methods.
Apply React best practices and language style guides in code.
Use store, actions and reducers in React.

2023-08-28 10:50 UTC, bellom commented
## Hi @DianaBeki  👏  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**CRR marked as invalid because of the following reasons stated below: 👇** 

**Kindly fix the linters error.**

Heads-up: It would be nice to add a unit test as stated in the [project requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=Testing%20requirements) to avoid a re-review.

Cheers and Happy coding!👏👏👏

2023-08-28 21:31 UTC, DianaBeki commented
Hello @bellom i have made all the required changes including linters. Kindly check my latest code I will appreciate

2023-08-29 11:30 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️

 Hello @DianaBeki ✋🏼 

_This is a manual review_


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._


___



[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-08-29 11:30 UTC, ahmetbozaci commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
According to the requirements kindly implement these;
- [ ] Deploy your website and put the link in the [readme](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=The%20project%20should,your%20README%20file.).
- [ ] Create a presentation video. [Requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=Once%20you%20have,a%20small%20picture.)

2023-08-29 11:30 UTC, ahmetbozaci commented on src/__tests__/MealDetails.test.js
> +/* eslint-disable */
OPTIONAL
- [ ] Kindly dont disable linters. Here is the [requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Do%20not%20disable%20Eslint%20or%20Stylint%20using%20inline%20comments%20within%20your%20code%20if%20not%20specified%20in%20the%20project%20requirement.)

2023-08-29 11:30 UTC, ahmetbozaci commented on src/__tests__/MealList.test.js
> +import axios from 'axios';
OPTIONAL
- [ ] Kindly dont disable linters. Here is the [requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Do%20not%20disable%20Eslint%20or%20Stylint%20using%20inline%20comments%20within%20your%20code%20if%20not%20specified%20in%20the%20project%20requirement.)

2023-08-29 11:30 UTC, ahmetbozaci commented on src/__tests__/mealSlice.test.js
> +import mealReducer, { fetchMeal } from '../redux/mealSlice';
OPTIONAL
- [ ] Kindly dont disable linters. Here is the [requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Do%20not%20disable%20Eslint%20or%20Stylint%20using%20inline%20comments%20within%20your%20code%20if%20not%20specified%20in%20the%20project%20requirement.)

2023-08-29 11:30 UTC, ahmetbozaci commented on README.md
> +
OPTIONAL
- [ ] If not have logo kindly delete it because it is broken now.

2023-08-29 11:30 UTC, ahmetbozaci commented on src/__tests__/MealList.test.js
> +
- [ ] Tests are not passed kindly fix it and test it before review.
![image](https://github.com/DianaBeki/meal_point/assets/38635158/cb65a825-20a7-4236-99c3-c35d0aab4057)

2023-09-04 11:28 UTC, merged